# Generated by Django 4.2.9 on 2024-01-30 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ingredient_recipe_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='Ingredients',
            new_name='ingredients',
        ),
    ]
